# Configuration file for Video Smart Cropper

# Detection Settings
detection:
  model_size: "yolov8n.pt"  # Options: yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  confidence: 0.5
  
# Ensemble Detection Settings (Higher Accuracy Mode)
ensemble:
  enabled: false  # Set to true for ensemble mode
  models:
    - yolo       # Fast and accurate
    - detr       # Transformer-based (Meta)
    - fasterrcnn # Traditional R-CNN
  voting_threshold: 2  # Minimum agreements (1-3)
  iou_threshold: 0.5   # IoU for matching detections
  
# Cropping Settings
cropping:
  default_format: "9:16"
  min_padding: 500  # Increased for better framing
  ideal_head_space: 0.15
  max_head_space: 0.25
  min_head_space: 0.05

# Text Detection Settings
text_detection:
  enabled: true
  languages: ["en", "tr"]
  min_text_area_ratio: 0.02
  subtitle_region_height: 0.3

# Processing Settings
processing:
  default_frame_interval: 30
  quality_threshold: 0.3
  jpeg_quality: 95
  use_quick_text_check: true

# Performance Settings
performance:
  use_gpu: true
  turbo_mode: true  # Enable optimized batch processing
  batch_size: 4     # Process 4 frames simultaneously

# Output Settings
output:
  create_subdirs: true
  subfolder_names:
    person: "persons"
    animal: "animals"
    object: "objects"
